apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    error_log /var/log/nginx-error.log info;
    events {}

    http {
        upstream backend {
          least_conn;
          server wordpress-service.default.svc.cluster.local:80;
        }

        server {
          listen 80;      
          server_name wordpress;
          location / {
            proxy_pass http://backend;
            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
          }
        }
    }