apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: frontend
        image: nginx
        volumeMounts:
          - name: nginx-cert-volume
            mountPath: /etc/ssl/certs
            readOnly: true
          - name: nginx-key-volume
            mountPath: /etc/ssl/private
            readOnly: true
          - name: nginx-config-volume
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
        ports:
        - containerPort: 80
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
        - name: nginx-cert-volume
          secret:
            secretName: nginx-secret
            items:
              - key: tls.crt
                path: example.com.crt
        - name: nginx-key-volume
          secret:
            secretName: nginx-secret
            items:
              - key: tls.key
                path: example.com.key
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
