apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    events {}

    http {
        upstream backend {
          least_conn;
          server backend:8080;
        }

        server {
          listen 80;

          server_name localhost;

          location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_buffering on;
          }
        }
    }