apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: backend
        image: wordpress
        envFrom:
          - configMapRef:
              name: wordpress-config
          - secretRef:
              name: wordpress-secret
        volumeMounts:
          - name: wordpress
            mountPath: /var/www
        ports:
        - containerPort: 80
      volumes:
        - name: wordpress
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  type: ClusterIP
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80